# Generated by Django 5.0.6 on 2024-06-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_registration',
            new_name='car_reg',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='car_type',
        ),
    ]
